test-runner: Output EAPP errors and check against them in log (#165)

diff --git a/tests/tests/Makefile b/tests/tests/Makefile
--- a/tests/tests/Makefile
+++ b/tests/tests/Makefile
@@ -29,6 +29,7 @@ all:  $(OBJS) $(SDK_HOST_LIB) $(SDK_EDGE_LIB) $(SDK_VERIFIER_LIB)
 	$(foreach test, $(TESTS), \
 		echo "echo 'testing $(test)'" >> test;\
 		echo "./$(RUNNER) $(test).eapp_riscv $(RUNTIME)" >> test; \
+		echo '[ $$? -eq 0 ] || echo "... ERROR"' >> test; \
 	)
 	chmod +x test
 
